name: TechTrends - Package with Docker

on:
  push:
    branches:
      - main

jobs:
  package-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ashkarn
          password: dckr_pat_h-KLWrhtN16yhgZ4XTTsNcBQJ8o

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ashkarn/techtrends:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}